name: Create release to Maven Central

on:
  push:
    tags:
      - 'v*'

env:
  PGP_SEC: ${{ secrets.PGP_SEC }}
  PGP_PASSWORD: ${{ secrets.PGP_PASSWORD }}
  OSSRH_USERNAME: ${{ secrets.SONATYPE_USER }}
  OSSRH_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  release:
    name: Build release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
        with:
          # release workflow should have access to all tags
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Status git before
        run: git status
      - uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
      # Until https://github.com/burrunan/gradle-cache-action/issues/42 is addressed, gradle should be run as a separate step
      - name: gradle release from tag
        # if workflow is triggered after push of a tag, deploy full release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: ./gradlew --build-cache -Prelease publishToSonatype
      - name: gradle snapshot release
        # if workflow is triggered after push to a branch, deploy snapshot
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        run: ./gradlew --build-cache -Prelease -Preckon.stage=snapshot publishToSonatype
        shell: bash
      - name: Status git after
        if: ${{ always() }}
        run: git status

  github_release:
    needs: release
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
